# builder stage

FROM node:18-slim AS builder

WORKDIR /workspace
# copy over all the files

COPY package*.json ./
COPY nx.json ./
COPY tsconfig*.json ./
COPY jest.config.ts ./
COPY jest.preset.js ./
COPY eslint.config.mjs ./
COPY webpack.*.config ./

COPY apps/jobber-auth ./apps/jobber-auth
COPY libs/graphql ./libs/graphql
COPY libs/grpc ./libs/grpc
COPY libs/nestjs ./libs/nestjs
COPY libs/prisma ./libs/prisma

RUN npm install --legacy-peer-deps

RUN apt-get update && apt-get install -y protobuf-compiler

RUN npx nx build jobber-auth

FROM node:18-slim AS runner

WORKDIR /app

# from root

COPY --from=builder /workspace/package.json ./
COPY --from=builder /workspace/package.lock.json ./

# from app

COPY --from=builder /workspace/apps/jobber-auth/package.json ./apps/job/package.json

# from library

COPY --from=builder /workspace/libs/graphql/package.json /workspace/libs/graphql/package.json
COPY --from=builder /workspace/libs/grpc/package.json /workspace/libs/grpc/package.json
COPY --from=builder /workspace/libs/nestjs/package.json /workspace/libs/nestjs/package.json
COPY --from=builder /workspace/libs/prisma/package.json /workspace/libs/prisma/package.json


# RUN apt-get update && apt-get install -y openssl

ENV NODE_ENV=production

RUN npm ci

COPY --from=builder /workspace/node_modules/@prisma-clients/jobber-auth/ ./node_modules/@prisma-clients/jobber-auth/

COPY --from=builder /workspace/dist ./dist

CMD ["node", "dist/app/jobber-auth"]